language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t joaogardenberg/testing-multi-docker-ci -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true joaogardenberg/testing-multi-docker-ci npm test
after_success:
  - docker build -t joaogardenberg/docker-course-client ./client
  - docker build -t joaogardenberg/docker-course-nginx ./nginx
  - docker build -t joaogardenberg/docker-course-api ./api
  - docker build -t joaogardenberg/docker-course-worker ./worker
  # Log into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push joaogardenberg/docker-course-client
  - docker push joaogardenberg/docker-course-nginx
  - docker push joaogardenberg/docker-course-api
  - docker push joaogardenberg/docker-course-worker
deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: testing-multi-docker-ci
  env: TestingMultiDockerCi-env
  bucket_name: elasticbeanstalk-sa-east-1-707041792727
  bucker_path: docker-course
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

